<?php

declare(strict_types=1);

namespace App\Core;

final class Session
{
    public function __construct(private readonly string $name)
    {
    }

    public function start(bool $secureCookie): void
    {
        if (session_status() === PHP_SESSION_ACTIVE) {
            return;
        }

        // strict mode rejects session ids not generated by the server,
        // closing the door on attacker-supplied ids (session fixation)
        ini_set('session.use_strict_mode', '1');
        session_name($this->name);
        session_set_cookie_params([
            'lifetime' => 0,
            'path' => '/',
            'httponly' => true,
            'samesite' => 'Lax',
            'secure' => $secureCookie,
        ]);
        session_start();
    }

    public function get(string $key): mixed
    {
        return $_SESSION[$key] ?? null;
    }

    public function set(string $key, mixed $value): void
    {
        $_SESSION[$key] = $value;
    }

    public function remove(string $key): void
    {
        unset($_SESSION[$key]);
    }

    public function regenerate(): void
    {
        if (session_status() === PHP_SESSION_ACTIVE) {
            session_regenerate_id(true);
        }
    }

    public function destroy(): void
    {
        $_SESSION = [];
        if (session_status() === PHP_SESSION_ACTIVE) {
            $params = session_get_cookie_params();
            setcookie($this->name, '', [
                'expires' => time() - 3600,
                'path' => $params['path'],
                'httponly' => $params['httponly'],
                'samesite' => $params['samesite'],
                'secure' => $params['secure'],
            ]);
            session_destroy();
        }
    }

    public function flash(string $key, mixed $value): void
    {
        $_SESSION['_flash'][$key] = $value;
    }

    public function pullFlash(string $key): mixed
    {
        $value = $_SESSION['_flash'][$key] ?? null;
        unset($_SESSION['_flash'][$key]);

        return $value;
    }
}
